services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres      # just the default, odoo will create its own
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 5s
      timeout: 5s
      retries: 5

  odoo18:
    image: rohanp1722/odoo-multi-version:18-latest
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./odoo-ci.conf:/etc/odoo/odoo.conf
    command: >
      odoo
      --db_host=postgres
      -d test_db_18          # odoo CREATES this automatically
      -i base
      --stop-after-init

  odoo19:
    image: rohanp1722/odoo-multi-version:19-latest
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./odoo-ci.conf:/etc/odoo/odoo.conf
    command: >
      odoo
      --db_host=postgres
      -d test_db_19          # odoo CREATES this automatically
      -i base
      --stop-after-init
