services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d test_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  odoo:
    build: .
    depends_on:
      postgres:
        condition: service_healthy

    environment:
      HOST: postgres
      USER: odoo
      PASSWORD: odoo

    command: >
      odoo
      --db_host=postgres
      --db_port=5432
      --db_user=odoo
      --db_password=odoo
      --database=test_db
      --db-filter=test_db
      -i base
      --test-enable
      --stop-after-init
