FROM odoo:18

USER root

RUN apt-get update && apt-get install -y \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /mnt/extra-addons && \
    chown -R odoo:odoo /mnt/extra-addons

USER odoo
