services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 5s
      timeout: 5s
      retries: 5

  odoo:
    build: .
    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - ./odoo-ci.conf:/etc/odoo/odoo.conf

    command: >
      odoo
      --db_host=postgres
      docker ps -a
      -d test_db
      -i base
      --stop-after-init
