[options]
admin_passwd = ${ODOO_ADMIN_PASSWD}
db_host = ${DB_HOST}
db_port = ${DB_PORT}
db_user = ${DB_USER}
db_password = ${DB_PASSWORD}
dbfilter = ^odoo18_.*
list_db = True
http_interface = 0.0.0.0
proxy_mode = True
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
