[options]
admin_passwd = Rohan@Odoo18#2024!
db_host = postgres
db_port = 5432
db_user = odoo
db_password = Rohan@DB#2024!
dbfilter = ^odoo18_.*
list_db = True
http_interface = 0.0.0.0
proxy_mode = True
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
