services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shared-db-network

volumes:
  postgres-data:

networks:
  shared-db-network:
    name: shared-db-network
