worker_processes 1;

events {
    worker_connections 1024;
}

http {

    upstream odoo {
        server odoo19-odoo19-1:8069;
        server odoo19-odoo19-2:8069;
        server odoo19-odoo19-3:8069;
    }

    upstream odoochat {
        server odoo19-odoo19-1:8072;
        server odoo19-odoo19-2:8072;
        server odoo19-odoo19-3:8072;
    }

    server {
        listen 80;

        proxy_read_timeout 720s;
        proxy_connect_timeout 720s;
        proxy_send_timeout 720s;

        client_max_body_size 200M;

        location / {
            proxy_pass http://odoo;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /websocket {
            proxy_pass http://odoochat;
            proxy_http_version 1.1;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

    }
}
