[options]
admin_passwd = Rohan@Odoo19#2024!
db_host = postgres
db_port = 5432
db_user = odoo
db_password = Rohan@DB#2024!
dbfilter = ^odoo19_.*
list_db = False
http_interface = 0.0.0.0
proxy_mode = True
