name: Odoo Docker CI/CD

on:
  push:
    branches:
      - main

jobs:

  docker-check:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt update
          sudo apt install docker-compose -y

      - name: Validate Odoo18 Compose
        run: |
          cd odoo18
          docker compose config

      - name: Validate Odoo19 Compose
        run: |
          cd odoo19
          docker compose config

      - name: Validate PostgreSQL Compose
        run: |
          cd postgres
          docker compose config

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/odoo-multi:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/odoo-multi:latest
